// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_chunk.proto

package chunk

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChunkPacketPB struct {
	BloomData            []byte   `protobuf:"bytes,1,opt,name=bloom_data,json=bloomData,proto3" json:"bloom_data,omitempty"`
	ChunkSize            int32    `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkId              int32    `protobuf:"varint,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ChunkHash            []byte   `protobuf:"bytes,4,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkPacketPB) Reset()         { *m = ChunkPacketPB{} }
func (m *ChunkPacketPB) String() string { return proto.CompactTextString(m) }
func (*ChunkPacketPB) ProtoMessage()    {}
func (*ChunkPacketPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_4104d644b38270d5, []int{0}
}

func (m *ChunkPacketPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkPacketPB.Unmarshal(m, b)
}
func (m *ChunkPacketPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkPacketPB.Marshal(b, m, deterministic)
}
func (m *ChunkPacketPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkPacketPB.Merge(m, src)
}
func (m *ChunkPacketPB) XXX_Size() int {
	return xxx_messageInfo_ChunkPacketPB.Size(m)
}
func (m *ChunkPacketPB) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkPacketPB.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkPacketPB proto.InternalMessageInfo

func (m *ChunkPacketPB) GetBloomData() []byte {
	if m != nil {
		return m.BloomData
	}
	return nil
}

func (m *ChunkPacketPB) GetChunkSize() int32 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func (m *ChunkPacketPB) GetChunkId() int32 {
	if m != nil {
		return m.ChunkId
	}
	return 0
}

func (m *ChunkPacketPB) GetChunkHash() []byte {
	if m != nil {
		return m.ChunkHash
	}
	return nil
}

func (m *ChunkPacketPB) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ChunkPacketPB)(nil), "chunk.ChunkPacketPB")
}

func init() { proto.RegisterFile("message_chunk.proto", fileDescriptor_4104d644b38270d5) }

var fileDescriptor_4104d644b38270d5 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x8d, 0x4f, 0xce, 0x28, 0xcd, 0xcb, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x73, 0x94, 0x66, 0x33, 0x72, 0xf1, 0x3a, 0x83, 0x58, 0x01, 0x89, 0xc9, 0xd9, 0xa9,
	0x25, 0x01, 0x4e, 0x42, 0xb2, 0x5c, 0x5c, 0x49, 0x39, 0xf9, 0xf9, 0xb9, 0xf1, 0x29, 0x89, 0x25,
	0x89, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x9c, 0x60, 0x11, 0x97, 0xc4, 0x92, 0x44, 0x90,
	0x34, 0x58, 0x67, 0x7c, 0x71, 0x66, 0x55, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x27,
	0x58, 0x24, 0x38, 0xb3, 0x2a, 0x55, 0x48, 0x92, 0x8b, 0x03, 0x22, 0x9d, 0x99, 0x22, 0xc1, 0x0c,
	0x96, 0x64, 0x07, 0xf3, 0x3d, 0x53, 0x10, 0x3a, 0x33, 0x12, 0x8b, 0x33, 0x24, 0x58, 0x20, 0x06,
	0x83, 0x45, 0x3c, 0x12, 0x8b, 0x33, 0x84, 0x84, 0xb8, 0x58, 0xc0, 0x36, 0xb2, 0x82, 0x25, 0xc0,
	0x6c, 0x27, 0xf6, 0x28, 0x88, 0x33, 0x93, 0xd8, 0xc0, 0x8e, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xe8, 0x52, 0x34, 0xf3, 0xcb, 0x00, 0x00, 0x00,
}
